name: CI

on:
  push:
    branches:
      - prebuild
  pull_request:

jobs:
  main:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        name:
          - darwin
          - linux
          - win32
        arch:
          - x64
          - arm64
        include:
          - name: darwin
            arch: x64
            os: macos-13
          - name: darwin
            arch: arm64
            os: macos-14
          - name: linux
            os: ubuntu-latest
          - name: win32
            os: windows-latest
        exclude:
          # node-gyp --arch=arm64 still produced x64 binaries.
          # Maybe use https://buildjet.com/for-github-actions/docs/about/pricing#arm?
          - name: linux
            arch: arm64
          # We'll build this with x64. There is need for a separate job.
          - name: win32
            arch: arm64

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      # Build and run tests.
      - run: yarn install --frozen-lockfile
      - run: yarn test

      # Build arm64 for Windows.
      - run: npx node-gyp rebuild --arch=${{ matrix.arch }}
        if: ${{ matrix.name == 'win32' && matrix.arch != 'arm64' }}
      - run: node scripts/build-sub-package.js ${{ matrix.arch }}
        if: ${{ matrix.name == 'win32' && matrix.arch != 'arm64' }}

      # Upload artifacts.
      - name: Upload node-pty-${{ matrix.name }}-${{ matrix.arch }}
        uses: actions/upload-artifact@v4
        with:
          name: node-pty-${{ matrix.name }}-${{ matrix.arch }}
          path: node_modules/@lydell/node-pty-${{ matrix.name }}-${{ matrix.arch }}
          if-no-files-found: error
