name: CI

on:
  push:
    branches:
      - prebuild
  pull_request:

jobs:
  main:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        name:
          - darwin
          - linux
          - win32
        include:
          - name: darwin
            os: macos-14
            arch: arm64
            arch2: x64
          - name: linux
            os: ubuntu-latest
            arch: x64
            # node-gyp --arch=arm64 still produced x64 binaries.
            # Maybe use https://buildjet.com/for-github-actions/docs/about/pricing#arm?
            arch2: none
          - name: win32
            os: windows-latest
            arch: x64
            arch2: arm64

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      # Build main arch and run tests.
      - run: yarn install --frozen-lockfile
      - run: yarn test

      # Build secondary arch.
      - run: npx node-gyp rebuild --arch=${{ matrix.arch2 }}
        if: ${{ matrix.arch2 != 'none' }}
      - run: node scripts/build-sub-package.js ${{ matrix.arch2 }}
        if: ${{ matrix.arch2 != 'none' }}

      # Upload artifacts.
      - name: Upload node-pty-${{ matrix.name }}-${{ matrix.arch }}
        uses: actions/upload-artifact@v4
        with:
          name: node-pty-${{ matrix.name }}-${{ matrix.arch }}
          path: node_modules/@lydell/node-pty-${{ matrix.name }}-${{ matrix.arch }}
          if-no-files-found: error
      - name: Upload node-pty-${{ matrix.name }}-${{ matrix.arch2 }}
        uses: actions/upload-artifact@v4
        with:
          name: node-pty-${{ matrix.name }}-${{ matrix.arch2 }}
          path: node_modules/@lydell/node-pty-${{ matrix.name }}-${{ matrix.arch2 }}
          if-no-files-found: error
        if: ${{ matrix.arch2 != 'none' }}

      # To download the artifacts for publishing:
      # rm -rf artifacts && gh run download RUN_ID --dir artifacts
